#!/bin/bash

__get_conainers() {
    $1 ps --format '{{.Label "crowdr.name"}}'
}

_crowdr() {
    local cur prev
    local commands=(
        build
        run
        stop
        ps
        ip
        shell
        exec
        pipe
        restart
        start
        stats
        kill
        rm
        rmi
        version
    )
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    case $prev in
        shell|pipe|exec)
            COMPREPLY=($(compgen -W "$(__get_conainers $1)" -- $cur))
            return 0
            ;;
    esac
    case $cur in
        shell|pipe|exec)
            COMPREPLY=($(__get_conainers $1))
            ;;
        *)
            COMPREPLY=($(compgen -W "${commands[*]}" -- $cur))
            ;;
    esac
    return 0
}

complete -F _crowdr crowdr ./crowdr
