#!/bin/bash

[[ -n "$CROWDR_TRACE" || -n "$CROWDR_DRY" ]] && set -x
if [[ ! -n "$CROWDR_CFG" ]]; then
    if [[ -d ".crowdr" ]]; then
        CROWDR_CFG=".crowdr/config.sh"
    else
        CROWDR_CFG="crowdr.cfg.sh"
    fi
fi
CROWDR_DIR="$(dirname $CROWDR_CFG)"
CROWDR_HOOKDIR="$CROWDR_DIR/hooks"
if [[ -n "$CROWDR_DRY" ]]; then
    EVAL='echo'
    HOOK_EXEC='cat'
else
    EVAL='eval'
    HOOK_EXEC='source'
fi
declare -A opts_run
declare -A opts_build
declare -A opts_image
declare -A opts_command
declare -A opts_hook
list=""

trap exit INT

fullname() {
    printf $name_format $project $1
}

run_hook(){
    local container="$1"
    local hook="$2"
    [[ -n ${opts_hook["${container}~$hook"]} ]] && ${opts_hook["${container}~$hook"]}
}

command_version() {
    echo "0.11.0"
}

command_build() {
    for c in $list; do
        if [[ -n "${opts_build[$c]}" ]]; then
            run_hook $c before.build
            $EVAL docker build -t $c ${opts_build[$c]} || exit
            run_hook $c after.build
        fi
    done
}

command_run() {
    #delete existent containers
    $EVAL docker inspect \
        --type=container \
        --format='{{.Name}}' \
        $(tac <<< "$list") \
        2> /dev/null \
        | sed 's|^/||' \
        | xargs --no-run-if-empty docker rm -f > /dev/null
    for c in $list; do
        run_hook $c before.run
        image=$c
        [[ -n "${opts_image[$c]}" ]] && image="${opts_image[$c]}"
        $EVAL docker run -d -t --name $c ${opts_run[$c]} "$image" ${opts_command[$c]} > /dev/null && echo $c
        run_hook $c after.run
    done
}

command_start() {
    $EVAL docker start $list
}

command_stop() {
    $EVAL docker stop $(tac <<< "$list")
}

command_stats() {
    $EVAL docker stats $list
}

command_ps() {
    local out="$($EVAL docker ps)"
    local list=""
    echo "$(head -1 <<< "$out")"
    list="$(awk -v regex="$project" '$NF ~ regex' <<< "$out")"
    [[ -n "$list" ]] && echo "$list"
}

command_ip() {
    local ip=""
    local running=""
    for c in $list; do
        running=$($EVAL docker inspect --format '{{.State.Running}}' $c)
        ip=$($EVAL docker inspect --format '{{ .NetworkSettings.IPAddress }}' $c)
        [[ "$running" == "false" ]] && ip=""
        printf '%-30s %-30s\n' $c "$ip"
    done
}

command_shell() {
    $EVAL docker exec -it $(fullname $1) bash
}

command_exec() {
    local name="$1"
    shift
    $EVAL docker exec -it $(fullname $name) "$@"
}

command_pipe() {
    local name="$1"
    shift
    $EVAL docker exec -i $(fullname $name) "$@"
}

command_restart() {
    echo "Stopping..."
    $EVAL docker stop $(tac <<< "$list")
    echo
    echo "Starting..."
    $EVAL docker start $list
}

command_kill() {
    $EVAL docker kill $(tac <<< "$list")
}

command_rm() {
    $EVAL docker rm $(tac <<< "$list")
}

command_rmi() {
    local image=""
    for c in $list; do
        run_hook $c before.rmi
        image=$c
        [[ -n "${opts_image[$c]}" ]] && image="${opts_image[$c]}"
        $EVAL docker rmi "${image}"
        run_hook $c after.rmi
    done
}

parse_cfg() {
    local container=""
    local option=""
    local value=""
    local link=""
    local alias=""
    local hook_name=""
    local hook_script=""
    local names=()
    source $CROWDR_CFG
    while read container option value; do
        container="$(fullname $container)"
        names+=("$container")
        case $option in
            command)
                opts_command[$container]=$value
                continue
                ;;
            image)
                opts_image[$container]=$value
                continue
                ;;
            build)
                opts_build[$container]=$value
                continue
                ;;
            link)
                link="${value%%:*}"
                link="$(fullname $link)"
                alias="${value##*:}"
                value="$link:$alias"
                ;;
            after.*|before.*)
                opts_hook["$container~$option"]="$value"
                continue
                ;;
        esac
        opts_run[$container]+=" --$option=$value"
    done < <(grep -vP '^#|^\S*$' <<< "$config")
    list="$(printf '%s\n' "${names[@]}" | uniq )"
}

cmd="${1:-run}"
shift
parse_cfg
[[ -x $CROWDR_HOOKDIR/before.$cmd ]] && $HOOK_EXEC $CROWDR_HOOKDIR/before.$cmd
command_$cmd "$@"
[[ -x $CROWDR_HOOKDIR/after.$cmd  ]] && $HOOK_EXEC $CROWDR_HOOKDIR/after.$cmd
exit 0
