#!/bin/bash

[[ -n "$CROWDR_TRACE" || -n "$CROWDR_DRY" ]] && set -x
if [[ ! -n "$CROWDR_CFG" ]]; then
    if [[ -d ".crowdr" ]]; then
        CROWDR_CFG=".crowdr/config.sh"
    else
        CROWDR_CFG="crowdr.cfg.sh"
    fi
fi
CROWDR_DIR="$(dirname $CROWDR_CFG)"
CROWDR_HOOKDIR="$CROWDR_DIR/hooks"
if [[ -n "$CROWDR_DRY" ]]; then
    DEBUG='echo'
    HOOK_EXEC='cat'
else
    HOOK_EXEC='source'
fi
declare -A opts_run
declare -A opts_build
declare -A opts_image
declare -A opts_command
declare -A opts_hook
declare -A names

trap exit INT

fullname() {
    printf $name_format $project $1
}

get_running_containers() {
    docker ps \
        --filter "label=crowdr.project=$project" \
        --format '{{.Names}}'
}

get_all_containers() {
    docker ps \
        --all \
        --filter "label=crowdr.project=$project" \
        --format '{{.Names}}'
}

run_hook(){
    local container="$1"
    local hook="$2"
    [[ -n ${opts_hook["${container}~$hook"]} ]] && ${opts_hook["${container}~$hook"]}
}

command_version() {
    echo "0.11.0"
}

command_build() {
    local container
    for container in ${!names[@]}; do
        if [[ -n "${opts_build[$container]}" ]]; then
            run_hook $container before.build
            $DEBUG docker build -t $container ${opts_build[$container]} || exit
            run_hook $container after.build
        fi
    done
}

command_run() {
    local image
    local container
    command_rm --force > /dev/null
    for container in ${!names[@]}; do
        run_hook $container before.run
        image=$container
        [[ -n "${opts_image[$container]}" ]] && image="${opts_image[$container]}"
        $DEBUG docker run \
            --label crowdr.project=$project \
            --label crowdr.name=${names[$container]} \
            --detach \
            --tty \
            --name $container \
            ${opts_run[$container]} \
            "$image" \
            ${opts_command[$container]} > /dev/null && echo $container
        run_hook $container after.run
    done
}

command_start() {
    local container
    for container in $(get_all_containers); do
        run_hook $container before.start
        $DEBUG docker start $container
        run_hook $container after.start
    done
}

command_stop() {
    local container
    for container in $(get_running_containers | tac); do
        run_hook $container before.stop
        $DEBUG docker stop $container
        run_hook $container after.stop
    done
}

command_stats() {
    $DEBUG docker stats $(get_all_containers)
}

command_ps() {
    $DEBUG docker ps --filter="label=crowdr.project=$project" "$@"
}

command_ip() {
    local containers=$(get_all_containers)
    if [[ "$containers" != "" ]]; then
        $DEBUG docker inspect \
            --format '{{printf "%-30s %-30s" .Name .NetworkSettings.IPAddress}}' \
            $containers
    fi
}

command_shell() {
    $DEBUG docker exec \
        --interactive \
        --tty \
        $1 bash
}

command_exec() {
    $DEBUG docker exec \
        --interactive \
        --tty \
        "$@"
}

command_pipe() {
    $DEBUG docker exec \
        --interactive \
        "$@"
}

command_restart() {
    echo "Stopping..."
    command_stop
    echo
    echo "Starting..."
    command_start
}

command_kill() {
    local container
    for container in $(get_running_containers | tac); do
        run_hook $container before.kill
        $DEBUG docker kill "$@" $container
        run_hook $container after.kill
    done
}

command_rm() {
    local container
    for container in $(get_all_containers | tac); do
        run_hook $container before.rm
        $DEBUG docker rm "$@" $container
        run_hook $container after.rm
    done
}

command_rmi() {
    local image
    local container
    for container in ${!names[@]}; do
        run_hook $container before.rmi
        image=$container
        [[ -n "${opts_image[$container]}" ]] && image="${opts_image[$container]}"
        $DEBUG docker rmi "${image}"
        run_hook $container after.rmi
    done
}

parse_cfg() {
    local container
    local option
    local value
    local link
    local alias
    local hook_name
    local hook_script
    local short_name
    source $CROWDR_CFG
    while read container option value; do
        short_name=$container
        container="$(fullname $container)"
        names[$container]=$short_name
        case $option in
            command)
                opts_command[$container]=$value
                continue
                ;;
            image)
                opts_image[$container]=$value
                continue
                ;;
            build)
                opts_build[$container]=$value
                continue
                ;;
            link)
                link="${value%%:*}"
                link="$(fullname $link)"
                alias="${value##*:}"
                value="$link:$alias"
                ;;
            after.*|before.*)
                opts_hook["$container~$option"]="$value"
                continue
                ;;
        esac
        opts_run[$container]+=" --$option=$value"
    done < <(grep -vP '^#|^\S*$' <<< "$config")
}

cmd="${1:-run}"
shift
parse_cfg
[[ -x $CROWDR_HOOKDIR/before.$cmd ]] && $HOOK_EXEC $CROWDR_HOOKDIR/before.$cmd
command_$cmd "$@"
[[ -x $CROWDR_HOOKDIR/after.$cmd  ]] && $HOOK_EXEC $CROWDR_HOOKDIR/after.$cmd
exit 0
